---
image:
  file: .gitpod.Dockerfile
tasks:
  - name: NixOS Shell
      command: |
      nix run .#nixosConfigurations.gitpod.config.system.build.toplevel

ports:
  - port: 2222
    onOpen: ignore
  - port: 8000-9000
    onOpen: ignore

vscode:
  extensions:
    - bbenoist.Nix
    - 1Password.op-vscode
