image:
  file: .gitpod.Dockerfile
tasks:
  - name: NixOS Shell
    command: |
      make start

ports:
  - port: 2222
    onOpen: ignore
  - port: 8000-9000
    onOpen: ignore

vscode:
  extensions:
    - bbenoist.Nix
