name: Run on .gitpod file change

on:
  push:
    paths:
      - '.gitpod.Dockerfile'
      - '.gitpod.yml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run some command
      run: gp validate
